# Generated by Django 4.2.25 on 2025-11-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Sex')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nin', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('gps_coodinates', models.CharField(blank=True, max_length=150, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('receive_sms_notifications', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accesslevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
