# Generated by Django 4.2.25 on 2025-11-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_type', models.CharField(choices=[('cash', 'Cash'), ('produce', 'Produce')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produce_type', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='system.farmer')),
            ],
            options={
                'verbose_name_plural': 'Credit',
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='CreditRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('produce', 'Produce')], max_length=50)),
                ('produce_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='system.credit')),
            ],
            options={
                'verbose_name_plural': 'Credit Repayment',
                'db_table': 'credit_repayment',
            },
        ),
    ]
