# Generated by Django 4.2.25 on 2025-11-17 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_credit_creditrepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('ORDER_DEBIT', 'Order Debit'), ('PRODUCE_CREDIT', 'Produce Credit'), ('CASH_CREDIT', 'Cash Credit Given'), ('PAYMENT', 'Payment Made by Farmer'), ('ADJUSTMENT', 'Adjustment')], max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile Money'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='system.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
